# Generated by Django 3.1.4 on 2020-12-04 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'ordering': ['-rank']},
        ),
        migrations.AddField(
            model_name='details',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='details',
            name='uuid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
