# Generated by Django 3.1.4 on 2020-12-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank_app', '0002_auto_20201204_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
